@REM Unreal Engine Build
echo ##CI_UE_HOME=C:\Program Files\Epic Games\UE_4.27

@REM Windows Publishing
echo ##APP_NAME=AliveHunter
echo ##APP_DESCRIPTION=App description.#
@REM The following is the app .exe generated by Unreal Engine build under Distribution\Windows
echo ##MSIX_EXE=AliveHunterReborn.exe
echo ##MSIX_RESOURCES=CI\shared\sample-pipelines\microsoft-store\resources#
echo ##MSIX_LOGO_44=SampleLogo44.png#
echo ##MSIX_LOGO_150=SampleLogo150.png#
echo ##MSIX_APPLOGO=SampleLogo200x150.png#
echo ##MSIX_BGCOLOR_HEX=464646#
echo ##PUBLISHER=ArsolidGames
echo ##PUBLISHER_ACCOUNT=ArsolidGames
echo ##PUBLISHER_FAMILY=22878ArsolidGames.AliveHunter_mf1d4ymgsz6sg
echo ##PUBLISHER_UUID=C3410D60-7869-4D9E-8C4D-A011E3FAFEBC